title: Vic Perdana's blog
description: A tech-focused blog for cloudy's folks - Cloud Solution Architect @ MSFT.  Content are my own opinion/experiences.
show_downloads: true
theme: jekyll-theme-cayman
