title: TechLand
author: Vic Perdana
navbar-links:
  About Me: "aboutme"
  Author's home: "https://vicperdana.com"

description: A tech-focused blog for cloudy's folks
show_downloads: true
domain: blog.vicperdana.com
url: https://blog.vicperdana.com
theme: jekyll-theme-cayman
linkedin_username: vperdana
twitter_username: vperdana
github_username: vicperdana
email: me@vicperdana.com
plugins:
- jekyll-feed
