title: TechLand
author:
  name: Vic Perdana
  email: me@vicperdana.com
description: > # this means to ignore newlines until "show_excerpts:"
  A tech-focused blog for cloudy's folks

url: "https://blog.vicperdana.com" 

show_excerpts: true # set to true to show excerpts on the homepage
addthis: true
disqus:
  shortname: blog-vicperdana-com
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %-b, %Y"
  skin: dark
  # generate social links in footer
  social_links:
    twitter: vperdana
    github:  vicperdana
    devto: vicperdana
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: vperdana
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
- about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag